name: Production
on:
  push:
    branches:
      - master
jobs:
  build-prod:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@master
      - name: Publish Production to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: paradewisudaitb/Line-Bot/wispril21-line-bot
          username: ${{ secrets.PACKAGE_USERNAME }}
          password: ${{ secrets.PACKAGE_PASSWORD }}
          registry: docker.pkg.github.com
          tags: "production"
  deploy-prod:
    runs-on: ubuntu-latest
    needs: [build-prod]
    steps:
      - name: Run deployment script over SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          port: 22
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: "docker-compose pull && docker-compose build && docker-compose up -d --remove-orphans"